### ISSUE TITLE
Extracting data using hmd.mx

### ISSUE THREAD

**Issue by petermcquire** [robjhyndman/demography#49]
When extracting data using hmd.mx I get the following error:

Error in function (type, msg, asError = TRUE)  : 
  Unknown SSL protocol error in connection to www.mortality.org:443 

I've used this hundreds of times, but probably not in last few months

**Comment by robjhyndman** [comment]
The current github version of the package is working. Here is the change that fixed the problem: https://github.com/robjhyndman/demography/commit/a139db76217779f77e34ae1ce3fc8cfb60635b83

You need to use login details for [former.mortality.org](http://former.mortality.org) instead of [www.mortality.org](http://www.mortality.org/). 

I have been waiting for mortality.org to announce their new API before updating on CRAN.

**Comment by filipeclduarte** [comment]
The [former.mortality.org](former.mortality.org) is not working at the moment.

**Comment by robjhyndman** [comment]
I'll update to use the new site and push to CRAN in the coming week.
